<a href="https://colab.research.google.com/github/aribxz/deep_learning/blob/main/Introduction%20to%20PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import random
import numpy as np
import torch.nn as nn
import torch.optim as optim

In [ ]:
print(f"CUDA available : {torch.cuda.is_available()}")

CUDA available : False


#1. Tensors

Patter 1: Direct creation from data

In [ ]:
data = [[1,2,3], [4,5,6]]
tensor = torch.tensor(data)
print(tensor)

tensor([[1, 2, 3],
        [4, 5, 6]])


Pattern 2: Creation from a desired shape

In [ ]:
shape = (5, 5)

ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)
random_tensor = torch.randn(shape)

print(ones_tensor)
print(zeros_tensor)
print(random_tensor)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
tensor([[ 0.3389,  0.8734,  1.4869,  0.6363,  0.1989],
        [ 0.7284,  0.6479,  0.4282, -0.1654, -0.2065],
        [ 0.5893,  0.6567, -0.2502, -0.5681,  0.2964],
        [ 0.4704,  0.3643,  0.7832, -0.6701,  0.1915],
        [ 1.0405,  1.0144,  0.0049, -1.1929,  0.6012]])


Pattern 3: Creation by mimicking another tensor

In [ ]:
template = torch.tensor([[1,2], [69, 420]])
r_tensor = torch.randn_like(template, dtype=torch.float)
print(r_tensor)

tensor([[-2.2478, -0.1556],
        [ 1.9709, -0.8748]])


The Three Critical Attributes: shape, dtype and device

In [ ]:
tensor = torch.randn(3,4)
print(tensor.shape)
print(tensor.dtype)
print(tensor.device)

torch.Size([3, 4])
torch.float32
cpu


# 2. Autograd

Data vs Parameter

In [ ]:
x = torch.tensor([[1, 3], [67, 88]])
w = torch.tensor([[1.0], [2.0]], requires_grad=True)

print(x, x.requires_grad)
print(w, w.requires_grad)


tensor([[ 1,  3],
        [67, 88]]) False
tensor([[1.],
        [2.]], requires_grad=True) True


In [ ]:
a = torch.tensor(2.0, requires_grad=True)
b = torch.tensor(3.0, requires_grad=True)
x = torch.tensor(4.0, requires_grad=True)

y = a + b
z = x * y

print(a.item(), b.item(), x.item())
print(y)
print(z)

2.0 3.0 4.0
tensor(5., grad_fn=<AddBackward0>)
tensor(20., grad_fn=<MulBackward0>)


#3. Bit of Matrix Multiplication & Optimization

Element-Wise Product

In [ ]:
A = torch.tensor([[1,2], [8,9]])
B = torch.tensor([[9,99], [999, 9999]])

element_wise_product = A * B
print(element_wise_product)

tensor([[    9,   198],
        [ 7992, 89991]])


Matrix Multiplication

In [ ]:
m1 = torch.randn(2,3)
m2 = torch.randn(3,2)

matrix_product = m1 @ m2
print(matrix_product)

tensor([[ 2.6343, -0.9219],
        [-1.8679,  1.8844]])


Reductions and the dim arguement

In [ ]:
scores = torch.tensor([[10.0, 20.0, 30.0],
                       [ 5.0, 10.0, 15.0]])

print(scores.mean())
print(scores.mean(dim=0)) # Row wise.
print(scores.mean(dim=1)) # Column wise.

tensor(15.)
tensor([ 7.5000, 15.0000, 22.5000])
tensor([20., 10.])


Argmax and Gather

In [ ]:
dm1 = torch.argmax(scores, dim=1) # Returns the index of the highest value.
print(dm1)

tensor([2, 2])


In [ ]:
data = torch.arange(12).reshape(3,4) # To get a very highly specific index.
print(data)

indices = torch.tensor([[2], [0], [3]])
selected = torch.gather(data, dim=1, index=indices)
print(selected)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([[ 2],
        [ 4],
        [11]])


# 4. Linear Regression Scratch

Create the data

In [ ]:
n = 10
d_in = 1
d_out = 1

x = torch.randn(n, d_in)

true_w = torch.tensor([[2.0]])
true_b = torch.tensor([1.0])

y_true = x @ true_w + true_b

print(f"n = {n}, d_in = {d_in}, d_out = {d_out}")
print(f"x.shape      = {tuple(x.shape)}")
print(f"y_true.shape = {tuple(y_true.shape)}")
print(f"true_w = {true_w.item()}, true_b = {true_b.item()}   (the secret answers)")

n = 10, d_in = 1, d_out = 1
x.shape      = (10, 1)
y_true.shape = (10, 1)
true_w = 2.0, true_b = 1.0   (the secret answers)


Initializing parameters

In [ ]:
w = torch.randn(d_in, d_out, requires_grad=True)
b = torch.randn(d_out, requires_grad=True)

print(f"initial w = {w.item():.4f}   (random guess)")
print(f"initial b = {b.item():.4f}   (random guess)")
print(f"w.requires_grad = {w.requires_grad}")
print(f"b.requires_grad = {b.requires_grad}")

initial w = -2.1042   (random guess)
initial b = 0.1643   (random guess)
w.requires_grad = True
b.requires_grad = True


The forward pass

In [ ]:
y_hat = x @ w + b

print("y_hat (predictions):")
print(y_hat)
print("\ny_true (the truth):")
print(y_true)

print("\nNotice y_hat has a grad_fn -- autograd is watching.")
print(f"y_hat.grad_fn = {y_hat.grad_fn}")

y_hat (predictions):
tensor([[ 3.0138],
        [-1.6759],
        [ 0.7680],
        [ 1.0009],
        [ 4.9582],
        [ 1.7391],
        [ 2.1667],
        [ 2.3004],
        [ 0.5276],
        [-0.7298]], grad_fn=<AddBackward0>)

y_true (the truth):
tensor([[-1.7083],
        [ 2.7491],
        [ 0.4262],
        [ 0.2049],
        [-3.5565],
        [-0.4968],
        [-0.9032],
        [-1.0302],
        [ 0.6547],
        [ 1.8499]])

Notice y_hat has a grad_fn -- autograd is watching.
y_hat.grad_fn = <AddBackward0 object at 0x7cd348fd25c0>


The Loss

In [ ]:
error = y_hat - y_true
squared_error_loss = error ** 2
loss = squared_error_loss.mean()

print(f"loss = {loss.item():.4f}")
print(f"loss.grad_fn = {loss.grad_fn}")
print("The loss sits at the very end of the computation graph.")
print("It is the source from which all knowledge will flow backward.")

loss = 14.7315
loss.grad_fn = <MeanBackward0 object at 0x7cd350e6a770>
The loss sits at the very end of the computation graph.
It is the source from which all knowledge will flow backward.


The Backward Pass

In [ ]:
loss.backward()

print(f"w.grad = {w.grad.item():.4f}")
print(f"b.grad = {b.grad.item():.4f}")
print()
print("The sign is everything:")
print("  A NEGATIVE gradient means increasing the parameter would DECREASE the loss.")
print("  The gradient always points toward the steepest INCREASE.")
print("  So to minimize the loss, we go in the OPPOSITE direction.")

w.grad = -7.8253
b.grad = 3.1758

The sign is everything:
  A NEGATIVE gradient means increasing the parameter would DECREASE the loss.
  The gradient always points toward the steepest INCREASE.
  So to minimize the loss, we go in the OPPOSITE direction.


Manual Gradient Descent

In [ ]:
learning_rate = 0.01

with torch.no_grad(): # Makes autograd not track this step
  w -= learning_rate * w.grad
  b -= learning_rate * b.grad

print(f"w updated: {w.item():.4f}")
print(f"b updated: {b.item():.4f}")

w.grad.zero_()
b.grad.zero_()

print(f"w.grad after zeroing: {w.grad.item():.4f}")
print(f"b.grad after zeroing: {b.grad.item():.4f}")

w updated: -1.9477
b updated: 0.1008
w.grad after zeroing: 0.0000
b.grad after zeroing: 0.0000


The full training loop

In [ ]:
torch.manual_seed(42)

w = torch.randn(d_in, d_out, requires_grad=True)
b = torch.randn(d_out, requires_grad=True)

epochs = 100
learning_rate = 0.01

for epoch in range(epochs):
  y_hat = x @ w + b

  error = y_hat - y_true
  squared_error_loss = error ** 2
  loss = squared_error_loss.mean()

  loss.backward()

  with torch.no_grad():
    w -= learning_rate * w.grad
    b -= learning_rate * b.grad

  w.grad.zero_()
  b.grad.zero_()

  if epoch % 10 == 0:
        print(f"{epoch:>6} | {loss.item():>10.4f} | {w.item():>10.4f} | {b.item():>10.4f}")

     0 |     2.0177 |     0.3621 |     0.1266
    10 |     1.4895 |     0.5874 |     0.1212
    20 |     1.1436 |     0.7695 |     0.1389
    30 |     0.9037 |     0.9187 |     0.1713
    40 |     0.7286 |     1.0427 |     0.2125
    50 |     0.5953 |     1.1473 |     0.2586
    60 |     0.4906 |     1.2365 |     0.3067
    70 |     0.4065 |     1.3135 |     0.3550
    80 |     0.3380 |     1.3806 |     0.4023
    90 |     0.2817 |     1.4396 |     0.4478


In [ ]:
print(f"learned w = {w.item():.4f}   (true w = {true_w.item():.4f})")
print(f"learned b = {b.item():.4f}   (true b = {true_b.item():.4f})")
print()
print("We built a learning machine from scratch.")

learned w = 1.4869   (true w = 2.0000)
learned b = 0.4868   (true b = 1.0000)

We built a learning machine from scratch.


# 5. NN Module Basics & Activation Functions

In [ ]:
d_in = 1
d_out = 1

linear_layer = nn.Linear(in_features=d_in, out_features=d_out) # y = x @ w + b
print(linear_layer.weight)
print(linear_layer.bias)

x = torch.randn(5, d_in)
y_hat = linear_layer(x)

print(f"\nx.shape     = {tuple(x.shape)}")
print(f"y_hat.shape = {tuple(y_hat.shape)}")
print("y_hat = linear_layer(x)  <- so much cleaner")

Parameter containing:
tensor([[0.9031]], requires_grad=True)
Parameter containing:
tensor([-0.8495], requires_grad=True)

x.shape     = (5, 1)
y_hat.shape = (5, 1)
y_hat = linear_layer(x)  <- so much cleaner


ReLU

In [ ]:
relu = nn.ReLU()

sample_data = torch.tensor([-1.0, 22.34, 5.66])
relu_output = relu(sample_data)

print(f"sample_data = {sample_data}")
print(f"relu_output = {relu_output}")

sample_data = tensor([-1.0000, 22.3400,  5.6600])
relu_output = tensor([ 0.0000, 22.3400,  5.6600])


Softmax

In [ ]:
softmax = nn.Softmax(dim = -1)

logits = torch.tensor([[-1.0, 22.34, 5.66], [22.334, 4.56, 69.69]])
probabilities = softmax(logits)

print("logits:")
print(logits)
print("\nsoftmax(logits):")
print(probabilities)
print()
print("Row sums (should be 1.0):")
print(probabilities.sum(dim=-1))
print()
print("The highest logit (4.0) became the highest probability.")
print("Every value is between 0 and 1, and each row sums to exactly 1.0.")

logits:
tensor([[-1.0000, 22.3400,  5.6600],
        [22.3340,  4.5600, 69.6900]])

softmax(logits):
tensor([[7.3041e-11, 1.0000e+00, 5.7012e-08],
        [2.7136e-21, 5.1808e-29, 1.0000e+00]])

Row sums (should be 1.0):
tensor([1., 1.])

The highest logit (4.0) became the highest probability.
Every value is between 0 and 1, and each row sums to exactly 1.0.


# 6. Advanced Layers

nn.Embedding: Turn words into numbers

In [ ]:
vocab_size = 10
embedding_dim = 3

embedding_layer = nn.Embedding(vocab_size, embedding_dim)
input_ids = torch.tensor([[1, 5, 9, 8]])

word_vectors = embedding_layer(input_ids)

print(f"vocab_size = {vocab_size}, embedding_dim = {embedding_dim}")
print(f"input_ids.shape    = {tuple(input_ids.shape)}")
print(f"word_vectors.shape = {tuple(word_vectors.shape)}")
print()
print("For each of our four input ids, it looked up and returned the")
print("corresponding three-dimensional vector.")
print()
print("word_vectors:")
print(word_vectors)
print()
print("This is the first step in every large language model.")

vocab_size = 10, embedding_dim = 3
input_ids.shape    = (1, 4)
word_vectors.shape = (1, 4, 3)

For each of our four input ids, it looked up and returned the
corresponding three-dimensional vector.

word_vectors:
tensor([[[ 0.3370,  0.9733, -1.0151],
         [ 0.0561,  0.7694,  2.5574],
         [ 0.0561,  0.3782,  0.7051],
         [ 1.7361,  1.8350,  0.8800]]], grad_fn=<EmbeddingBackward0>)

This is the first step in every large language model.


nn.LayerNorm: The traffic cap

In [ ]:
norm_layer = nn.LayerNorm(normalized_shape=3) # 3 is just the number of columns

sample_features = torch.randn(2, 3)
normalized = norm_layer(sample_features)

print("sample_features:")
print(sample_features)
print(f"\nmean per row: {sample_features.mean(dim=-1).tolist()}")
print(f"std  per row: {sample_features.std(dim=-1).tolist()}")
print()
print("normalized:")
print(normalized)
print(f"\nmean per row: {normalized.mean(dim=-1).tolist()}   <- basically zero")
print(f"std  per row: {normalized.std(dim=-1, unbiased=False).tolist()}   <- basically one")
print()
print("It keeps the network stable. It's beautiful.")

sample_features:
tensor([[-0.4908,  0.7049,  1.5278],
        [-0.3319,  1.6391,  0.8178]])

mean per row: [0.5806698799133301, 0.7082999348640442]
std  per row: [1.0150275230407715, 0.9900524020195007]

normalized:
tensor([[-1.2928,  0.1499,  1.1429],
        [-1.2868,  1.1514,  0.1354]], grad_fn=<NativeLayerNormBackward0>)

mean per row: [-3.973643103449831e-08, 3.973643103449831e-08]   <- basically zero
std  per row: [0.9999926686286926, 0.9999924302101135]   <- basically one

It keeps the network stable. It's beautiful.


nn.Dropout: Prevent Overfitting

In [ ]:
dropout_layer = nn.Dropout(p=0.5)
input_tensor = torch.ones(5)

print("input_tensor (all ones):")
print(input_tensor)

dropout_layer.train()
train_output = dropout_layer(input_tensor)
print("\n--- dropout_layer.train() ---")
print("train_output:")
print(train_output)
print("Randomly zeroed and scaled. Some values are zero, others are two.")

dropout_layer.eval()
eval_output = dropout_layer(input_tensor)

print("\n--- dropout_layer.eval() ---")
print("eval_output:")
print(eval_output)
print("It's the identity function. It just passes the original tensor through.")
print()
print("This simple on/off switch is a cornerstone of modern deep learning.")


input_tensor (all ones):
tensor([1., 1., 1., 1., 1.])

--- dropout_layer.train() ---
train_output:
tensor([2., 2., 2., 0., 0.])
Randomly zeroed and scaled. Some values are zero, others are two.

--- dropout_layer.eval() ---
eval_output:
tensor([1., 1., 1., 1., 1.])
It's the identity function. It just passes the original tensor through.

This simple on/off switch is a cornerstone of modern deep learning.


#7. The Professional Result

In [ ]:
class LinearRegressionModel(nn.Module):
  def __init__(self, in_features, out_features):
    super().__init__()
    self.linear_layer = nn.Linear(in_features, out_features)

  def forward(self, x):
    y_hat = self.linear_layer(x)
    return y_hat

model = LinearRegressionModel(in_features = 1, out_features = 1)
print("Model Architecture : ")
print(model)

Model Architecture : 
LinearRegressionModel(
  (linear_layer): Linear(in_features=1, out_features=1, bias=True)
)


The Optimizer

In [ ]:
learning_rate = 0.01
optimizer = optim.Adam(model.parameters(), lr = learning_rate)
loss_fn = nn.MSELoss()

MSELoss()


In [ ]:
epochs = 100
x = torch.randn(10, 1)

true_w = torch.tensor([[2.0]])
true_b = torch.tensor([1.0])

y_true = x @ true_w + true_b

for epoch in range(epochs):
  y_hat = model(x)
  loss = loss_fn(y_hat, y_true)

  optimizer.zero_grad()
  loss.backward()
  optimizer.step()

  if epoch % 10 == 0:
    print(f"Epoch {epoch:02d}: Loss = {loss.item():.4f}")

Epoch 00: Loss = 2.1968
Epoch 10: Loss = 1.7230
Epoch 20: Loss = 1.3172
Epoch 30: Loss = 0.9823
Epoch 40: Loss = 0.7155
Epoch 50: Loss = 0.5101
Epoch 60: Loss = 0.3569
Epoch 70: Loss = 0.2459
Epoch 80: Loss = 0.1679
Epoch 90: Loss = 0.1143


## The whole pipeline in basically 5 steps:

### 1. Compute y-hat.
### 2. Find error.
### 3. optimizer.zero_grad()
### 4. loss.backward()
### 5. optimizer.step()